Repository red-hat-storage/odf-operator, pull requests merged in 2021-09, with the labels that each got.

#83 docs: Update README
  README.md
Labels: lgtm, approved, backport-release-4.9

#84 Add description in the console installation wizard
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.csv.card-description.yaml
  config/manifests/bases/odf-operator.csv.icon.yaml
  config/manifests/kustomization.yaml
Labels: lgtm, approved, backport-release-4.9

#86 Update IBM console and CSV version to 0.2.1
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/kustomization.yaml
  config/manager/manager.env
  hack/make-bundle-vars.mk
Labels: lgtm, approved, backport-release-4.9

#87 docs: Update contribution guide
  CONTRIBUTING.md
Labels: lgtm, approved

#89 makefile: Update locations of the dependent images
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#91 docs: Add guidelines for updating CSV in CONTRIBUTING guide
  CONTRIBUTING.md
Labels: lgtm, approved

#92 action: Fix the commitlint action for signed-off
  .github/workflows/commitlint.yaml
  .github/workflows/conf/commitlintrc.json
Labels: lgtm, approved

#81 Delete quickstarts when removing StorageSystem
  controllers/delete.go
  controllers/quickstarts.go
  controllers/quickstarts_test.go
Labels: lgtm, approved, ok-to-test, backport-release-4.9

#95 Add RelatedResources in the status of StorageSystem
  Makefile
  api/v1alpha1/storagesystem_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf.openshift.io_storagesystems.yaml
  config/crd/bases/odf.openshift.io_storagesystems.yaml
  config/manager/manager.env
  controllers/defaults.go
  controllers/storagesystem_controller.go
  controllers/subscriptions.go
  controllers/subscriptions_test.go
  controllers/vendors.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, backport-release-4.9

#94 console: remove ibm-console container from odf-console deployement
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  console/console.go
  hack/make-bundle-vars.mk
  main.go
Labels: lgtm, approved, backport-release-4.9

#98 Bug 2004824: [release 4.9] console: remove ibm-console container from odf-console deployement
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  console/console.go
  hack/make-bundle-vars.mk
  main.go
Labels: lgtm, approved, bugzilla/severity-urgent, bugzilla/valid-bug

#99 Manage dependency Subscriptions directly
  Dockerfile
  Makefile
  api/v1alpha1/storagesystem_types.go
  bundle.Dockerfile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/metadata/dependencies.yaml
  config/manager/controller_manager_config.yaml
  config/manager/manager.env
  config/manager/manager.yaml
  controllers/defaults.go
  controllers/delete_test.go
  controllers/flashsystemcluster.go
  controllers/quickstarts_test.go
  controllers/storagecluster_controller_fake.go
  controllers/storagecluster_controller_test.go
  controllers/storagesystem_controller_fake.go
  controllers/subscriptions.go
  controllers/subscriptions_test.go
  controllers/suite_test.go
  controllers/vendors.go
  controllers/vendors_test.go
  hack/make-bundle-vars.mk
  main.go
  webhook/subscription/mutatingwebhook.go
  webhook/subscription/mutatingwebhook_test.go
  webhook/subscription/validatingwebhook.go
  webhook/subscription/validatingwebhook_test.go
Labels: lgtm, approved, backport-release-4.9

#102 Bug 2000143: [release-4.9] Manage dependency Subscriptions directly
  Dockerfile
  Makefile
  api/v1alpha1/storagesystem_types.go
  bundle.Dockerfile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/metadata/dependencies.yaml
  config/manager/controller_manager_config.yaml
  config/manager/manager.env
  config/manager/manager.yaml
  controllers/defaults.go
  controllers/delete_test.go
  controllers/flashsystemcluster.go
  controllers/quickstarts_test.go
  controllers/storagecluster_controller_fake.go
  controllers/storagecluster_controller_test.go
  controllers/storagesystem_controller_fake.go
  controllers/subscriptions.go
  controllers/subscriptions_test.go
  controllers/suite_test.go
  controllers/vendors.go
  controllers/vendors_test.go
  hack/make-bundle-vars.mk
  main.go
  webhook/subscription/mutatingwebhook.go
  webhook/subscription/mutatingwebhook_test.go
  webhook/subscription/validatingwebhook.go
  webhook/subscription/validatingwebhook_test.go
Labels: lgtm, approved, bugzilla/severity-urgent, bugzilla/valid-bug
