Repository red-hat-storage/odf-operator, pull requests merged in 2021-08, with the labels that each got.

#16 Create StorageCluster controller
  PROJECT
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/storagecluster_controller.go
  controllers/storagecluster_controller_fake.go
  controllers/storagecluster_controller_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#43 update phase in the status of storagesystem
  api/v1alpha1/storagesystem_types.go
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/storagesystem_controller.go
  controllers/subscriptions.go
Labels: approved, lgtm

#47 controllers: use env var instead of hardcoded values
  controllers/defaults.go
  controllers/flashsystemcluster.go
  controllers/subscriptions.go
Labels: approved, lgtm

#51 Add a method to feed env variables to the configmap of manager
  Dockerfile
  Makefile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.env
  config/manager/manager.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#52 controllers: Fix scheme issue via adding ibm scheme
  main.go
Labels: approved

#30 Add metrics for StorageSystem spec
  Dockerfile
  controllers/storagesystem_controller.go
  go.mod
  metrics/metrics.go
  metrics/metrics_test.go
Labels: lgtm, approved

#36 Add initialization code for ODF Console
  Dockerfile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/kustomization.yaml
  console/console.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#59 action: Add console,metrics as a type in the commitlintrc
  .github/workflows/conf/commitlintrc.json
  CONTRIBUTING.md
Labels: lgtm, approved

#55 set phase error if spec validation fails
  api/v1alpha1/storagesystem_types.go
  controllers/storagesystem_controller.go
Labels: lgtm, approved

#54 controllers: Append "-storagesystem" while creating storagesystem
  controllers/storagecluster_controller.go
  controllers/storagecluster_controller_test.go
Labels: lgtm, approved

#56 set kube-rbac-proxy image via kustomize with make target
  Makefile
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#58 controllers: Generate events for the storagesystem and storagecluster
  controllers/events.go
  controllers/events_test.go
  controllers/storagecluster_controller.go
  controllers/storagecluster_controller_fake.go
  controllers/storagesystem_controller.go
  controllers/storagesystem_controller_fake.go
  main.go
Labels: lgtm, approved

#57 bundle: update ocs dependencies version
  bundle/metadata/dependencies.yaml
Labels: lgtm, approved

#61 Bug 1994261: Add required permissions for console to initialize properly
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/role.yaml
  console/console.go
Labels: lgtm, approved, bugzilla/severity-urgent, bugzilla/valid-bug

#62 bundle: create a namespace automatically via UI if not one present
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#63 Add required information in the CSV to show in the UI
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#66 Update ODF QuickStart
  controllers/quickstart_constants.go
Labels: lgtm, approved, ok-to-test

#68 bundle: Update CSV to use official console image and add console annotation
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#69 use kustomize to generate the images of console
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/console/kustomization.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#70 update samples of storagesystem
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/samples/ibm-flashsystemcluster-storagesystem.yaml
  config/samples/kustomization.yaml
  config/samples/ocs-storagecluster-storagesystem.yaml
  config/samples/odf_v1alpha1_storagesystem.yaml
Labels: lgtm, approved

#60 config: Add resources to enable Prometheus Monitoring
  bundle/manifests/odf-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/odf-operator-controller-manager-metrics-service_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/odf-operator-controller-manager-metrics-service_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/default/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_service_role.yaml
  config/rbac/metrics_service_role_binding.yaml
Labels: lgtm, approved, ok-to-test

#72 console: Fix PodSelector label
  console/console.go
Labels: lgtm, approved

#74 bundle: Add vendor kind annotation to the csv
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#75 bundle: Change odf-catalogsource namespace
  config/install/ibm-storage-odf-operator-subscription.yaml
  config/install/odf-catalogsource.yaml
  config/install/odf-operator-subscription.yaml
Labels: lgtm, approved

#71 controllers: Add and update conditions in storageSystem controller
  api/v1alpha1/storagesystem_types.go
  bundle/manifests/odf.openshift.io_storagesystems.yaml
  config/crd/bases/odf.openshift.io_storagesystems.yaml
  controllers/conditions.go
  controllers/storagesystem_controller.go
  controllers/subscriptions.go
  controllers/vendor_test.go
  controllers/vendors.go
Labels: lgtm, approved

#76 bundle: Update csv version to 4.9.0
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/install/odf-operator-subscription.yaml
  hack/make-bundle-vars.mk
Labels: approved

#77 bundle: remove not required files from the bundle
  bundle/manifests/odf-operator-webhook-service_v1_service.yaml
Labels: approved

#64 Add noobaa as a dependency
  bundle/metadata/dependencies.yaml
  hack/make-bundle-vars.mk
Labels: approved

#78 Change default value of IBM_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: approved
