Repository red-hat-storage/odf-operator, pull requests merged in 2022-06, with the labels that each got.

#221 bundle: Add csi-addons to the dependencies.yaml
  bundle/metadata/dependencies.yaml
  controllers/subscriptions.go
Labels: lgtm, approved, backport-release-4.10, backport-release-4.11

#223 Bug 2093205:[release-4.10] bundle: Add csi-addons to the dependencies.yaml
  bundle/metadata/dependencies.yaml
  controllers/subscriptions.go
Labels: lgtm, approved, bugzilla/severity-urgent, bugzilla/valid-bug

#225 bundle: use extra label for odf-operator configs
  bundle/manifests/odf-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/odf-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/service.yaml
Labels: lgtm, approved
