Repository red-hat-storage/odf-operator, pull requests merged in 2022-08, with the labels that each got.

#233 Several pent up frustrations ;)
  .github/workflows/conf/commitlintrc.json
  .github/workflows/golangci-lint.yaml
  Dockerfile
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
  controllers/suite_test.go
  hack/e2e-test.sh
  hack/go-test-setup.sh
  hack/go-test.sh
  hack/make-bundle-vars.mk
  hack/make-project-vars.mk
  hack/make-tools.mk
  index.Dockerfile
Labels: lgtm, approved

#234 bundle: update quotes in the valid-subscription annotation
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved, backport-release-4.11

#232 controllers: Add namespace as list option while listing resources
  controllers/delete.go
  controllers/quickstarts.go
  controllers/subscription_controller.go
  controllers/subscriptions.go
Labels: lgtm, approved

#236 bundle: update ibm csv versions for 4.11
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, backport-release-4.11

#239 controllers: Do not verify IBM CSI driver CSV version
  Makefile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  controllers/defaults.go
  controllers/subscriptions.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, backport-release-4.10, backport-release-4.11

#238 update securityContext in all containers
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#241 Bug 2104836:[release-4.10] update ibm CSV versions
  Makefile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  controllers/defaults.go
  controllers/subscriptions.go
  hack/make-bundle-vars.mk
Labels: approved, bugzilla/valid-bug, bugzilla/severity-medium

#243 makefile: fix lint Makefile target and update all actions versions
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/mirror-noobaa-upstream-images.yaml
  .github/workflows/yamllint.yaml
  Makefile
  hack/make-project-vars.mk
Labels: lgtm, approved
