Repository red-hat-storage/odf-operator, pull requests merged in 2022-09, with the labels that each got.

#247 Prevent subscription config override if it is not empty
  controllers/subscriptions.go
Labels: lgtm, approved, ok-to-test

#249 update github actions
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/dependencies.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/mirror-noobaa-upstream-images.yaml
  .github/workflows/yamllint.yaml
Labels: lgtm, approved

#253 action: update github actions for release-4.10
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/conf/commitlintrc.json
  .github/workflows/dependencies.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/mirror-noobaa-upstream-images.yaml
  .github/workflows/yamllint.yaml
  controllers/suite_test.go
Labels: lgtm, approved, bugzilla/valid-bug

#252 action: update github actions for release-4.11
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/conf/commitlintrc.json
  .github/workflows/dependencies.yaml
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/mirror-noobaa-upstream-images.yaml
  .github/workflows/yamllint.yaml
  controllers/suite_test.go
Labels: lgtm, approved, bugzilla/valid-bug

#255 controllers: fix go fmt issue
  controllers/suite_test.go
Labels: lgtm, approved

#256 make required changes for the bundle and e2e tests
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/default/kustomization.yaml
  index.Dockerfile
  pkg/deploymanager/namespace.go
Labels: lgtm, approved

#258 bundle: start creating file based catalog instead of sqlite
  .github/workflows/docker-build.yaml
  Makefile
  catalog.Dockerfile
  catalog/index.yaml
  hack/make-bundle-vars.mk
  index.Dockerfile
Labels: lgtm, approved

#261 render the bundle images outside of the container
  .github/workflows/conf/commitlintrc.json
  .github/workflows/docker-build.yaml
  CONTRIBUTING.md
  Makefile
  catalog.Dockerfile
  catalog/bundle.yaml
  hack/make-bundle-vars.mk
  hack/make-tools.mk
Labels: lgtm, approved

#260 controllers: limit leaderElection & cache to operator namespace
  main.go
  pkg/util/openshift.go
Labels: lgtm, approved

#263 console: update compatibility support matrix for 4.12
  console/console.go
Labels: lgtm, approved

#264 makefile: build on ARM64 machine
  hack/make-project-vars.mk
Labels: lgtm, approved
