Repository red-hat-storage/odf-operator, pull requests merged in 2022-01, with the labels that each got.

#156 controllers: remove StorageClass encryption page from ODF QuickStart guide
  controllers/quickstart_constants.go
Labels: lgtm, approved

#164 Bug 2031876:[release-4.9]godeps: update ocs-operator API
  .github/workflows/docker-build.yaml
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#165 Add csi-addons to odf-operator
  Makefile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  controllers/defaults.go
  controllers/subscriptions.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#166 controllers: remove odf CSV as a owner to other CSV's and add odf sub
  controllers/subscriptions.go
Labels: lgtm, approved, backport-release-4.9

#168 bundle: update bundle manifests
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
Labels: lgtm, approved

#169 make: updates the csiaddons tag
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#170 controllers: start filtering odf sub instead of using static name
  Makefile
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  config/manager/manager.env
  controllers/defaults.go
  controllers/subscriptions.go
  controllers/subscriptions_test.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#171 makefile: make required changes for release-4.10
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  config/manager/manager.env
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#172 controllers: change controller ref to owner ref of the vendor system
  controllers/vendors.go
Labels: lgtm, approved
