Repository red-hat-storage/odf-operator, pull requests merged in 2023-07, with the labels that each got.

#320 Bug 2213450:[release-4.10] makefile: block OCP upgrades beyond the X+1 version
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#319 Bug 2213451:[release-4.11] makefile: block OCP upgrades beyond the X+1 version
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#318 Bug 2213452:[release-4.12] makefile: block OCP upgrades beyond the X+1 version
  Makefile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/kustomization.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#325 Revert "makefile: add fusion bases required to generate fusion bundle"
  Makefile
  config/manifests/fusion/kustomization.yaml
  config/manifests/fusion/odf-operator.clusterserviceversion.yaml
  config/manifests/fusion/odf-operator.csv.card-description.yaml
  config/manifests/fusion/odf-operator.csv.icon.yaml
  config/manifests/kustomization.yaml
Labels: lgtm, approved

#326 makefile: update operator-sdk version
  .github/workflows/docker-build.yaml
  bundle.Dockerfile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/manifests/odf.openshift.io_storagesystems.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/odf.openshift.io_storagesystems.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/suite_test.go
  hack/make-bundle-vars.mk
  hack/make-tools.mk
Labels: lgtm, approved

#328 console: update compatibility support matrix for 4.14
  console/console.go
Labels: lgtm, approved

#329 Bug 2222863:[release-4.10] bundle: add the valid-subscription annotation
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/severity-urgent, bugzilla/valid-bug

#330 godeps: update k8s godeps to v0.26.4
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: lgtm, approved

#327 makefile: update csv version
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/dependencies.yaml
  catalog/index.yaml
  config/manager/manager.env
  config/manifests/bases/kustomization.yaml
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#331 catalog: remove catalog manifests and add them in gitignore
  .gitignore
  catalog/csiaddons.yaml
  catalog/ibm.yaml
  catalog/noobaa.yaml
  catalog/ocs.yaml
  catalog/odf.yaml
Labels: lgtm, approved

#332 godeps: update go version
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/golangci-lint.yaml
  Dockerfile
  go.mod
Labels: lgtm, approved
