Repository red-hat-storage/odf-operator, pull requests merged in 2023-02, with the labels that each got.

#283 revert the changes made for the fusion bundle
  .gitignore
  Makefile
  config/fusion/bases/fdf-operator.clusterserviceversion.yaml
  config/fusion/bases/fdf-operator.csv.card-description.yaml
  config/fusion/bases/fdf-operator.csv.icon.yaml
  config/fusion/bases/kustomization.yaml
  config/fusion/kustomization.yaml
Labels: lgtm, approved

#284 makefile: add fusion bases required to generate fusion bundle
  Makefile
  config/manifests/fusion/kustomization.yaml
  config/manifests/fusion/odf-operator.clusterserviceversion.yaml
  config/manifests/fusion/odf-operator.csv.card-description.yaml
  config/manifests/fusion/odf-operator.csv.icon.yaml
  config/manifests/kustomization.yaml
Labels: lgtm, approved

#287 console: configure securityContext for odf-console
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
Labels: lgtm, approved

#289 Revert "console: configure securityContext for odf-console"
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
Labels: lgtm, approved

#288 action: check for uncommitted bundle changes
  .github/workflows/docker-build.yaml
Labels: lgtm, approved

#290 Add/update securityContext for containers
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#293 Bug 2168035:[release-4.11] bundle: remove debug logging from the manager auth proxy patch
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, jira/valid-bug

#294 console: update compatibility support matrix for 4.13
  console/console.go
Labels: lgtm, approved

#295 Bug 2168036:[release-4.10] bundle: remove debug logging from the manager auth proxy patch
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
