Repository red-hat-storage/odf-operator, pull requests merged in 2024-09, with the labels that each got.

#473 bundle: Stop service account token from being automatically mounted in odf-console
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
Labels: lgtm, approved

#476 Syncing latest changes from main for odf-operator
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/console/console_init.yaml
Labels: lgtm, approved

#477 makefile: update csi-addons version to v0.10.0
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/metadata/dependencies.yaml
  catalog/csiaddons.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#480 catalog: update catalog files
  catalog/recipe.yaml
Labels: lgtm, approved

#420 Bug 2296536: [release-4.12] api: update ocs-operator pkg version
  go.mod
  go.sum
  vendor/github.com/red-hat-storage/ocs-operator/api/v1/ocsinitialization_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v1/zz_generated.deepcopy.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#478 Syncing latest changes from main for odf-operator
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/metadata/dependencies.yaml
  catalog/csiaddons.yaml
  catalog/index.yaml
  catalog/recipe.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#488 [release-4.13] makefile: pin gingko version in tools script
  hack/make-tools.mk
Labels: lgtm, approved, bugzilla/valid-bug

#484 pin gingko version in tools script
  hack/make-tools.mk
Labels: lgtm, approved

#485 [release-4.16] makefile: pin gingko version in tools script
  hack/make-tools.mk
Labels: lgtm, approved, bugzilla/valid-bug

#486 [release-4.15] makefile: pin gingko version in tools script
  hack/make-tools.mk
Labels: lgtm, approved, bugzilla/valid-bug

#424 Bug 2296521: [release-4.16] api: update ocs-operator pkg version
  go.mod
  go.sum
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#490 Syncing latest changes from main for odf-operator
  hack/make-tools.mk
Labels: lgtm, approved
