Repository red-hat-storage/odf-operator, pull requests merged in 2024-10, with the labels that each got.

#479 update ibm odf operator to 1.6.0
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  go.mod
  go.sum
  hack/make-bundle-vars.mk
  hack/make-project-vars.mk
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: lgtm, approved

#423 Bug 2296522: [release-4.15] api: update ocs-operator pkg version
  go.mod
  go.sum
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/storagecluster_types.go
  vendor/github.com/red-hat-storage/ocs-operator/api/v4/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#482 Bug 2314668:[release-4.14] update ibm odf operator to 1.5.1
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  go.mod
  go.sum
  hack/make-bundle-vars.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#491 Bug 2315707:[release-4.15] update ibm odf operator to 1.6.0 and apis to 1.5.1
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  go.mod
  go.sum
  hack/make-bundle-vars.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#497 catalog: update recipe bundle
  catalog/recipe.yaml
Labels: lgtm, approved

#496 Syncing latest changes from main for odf-operator
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  catalog/recipe.yaml
  config/manager/manager.env
  controllers/defaults.go
  go.mod
  go.sum
  hack/make-bundle-vars.mk
  hack/make-project-vars.mk
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: lgtm, approved
