Repository red-hat-storage/odf-operator, pull requests merged in 2024-07, with the labels that each got.

#433 hack: update the aws cleanup script to delete few other resources
  hack/aws-cleanup.sh
Labels: lgtm, approved

#435 Syncing latest changes from main for odf-operator
  hack/aws-cleanup.sh
Labels: lgtm, approved

#438 Syncing latest changes from main for odf-operator
  console/console.go
Labels: lgtm, approved

#440 [release-4.15] create a mechanism to deploy odf using operator-sdk
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .gitignore
  Makefile
  bundle.Dockerfile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  catalog.deps.Dockerfile
  catalog/csiaddons.yaml
  catalog/ibm.yaml
  catalog/noobaa.yaml
  catalog/ocs.yaml
  e2e/setup_teardown.go
  hack/install-odf.sh
  hack/make-bundle-vars.mk
  hack/make-tools.mk
Labels: lgtm, approved, bugzilla/valid-bug

#448 [release-4.13] create a mechanism to deploy odf using operator-sdk
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .gitignore
  Makefile
  bundle.Dockerfile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  catalog.deps.Dockerfile
  catalog/ibm.yaml
  catalog/odf.yaml
  e2e/setup_teardown.go
  hack/install-odf.sh
  hack/make-bundle-vars.mk
  hack/make-tools.mk
Labels: lgtm, approved, bugzilla/valid-bug

#449 [release-4.12] create a mechanism to deploy odf using operator-sdk
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .gitignore
  Makefile
  bundle.Dockerfile
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  catalog.deps.Dockerfile
  catalog/bundle.yaml
  catalog/csiaddons.yaml
  catalog/ibm.yaml
  catalog/noobaa.yaml
  catalog/ocs.yaml
  e2e/setup_teardown.go
  hack/install-odf.sh
  hack/make-bundle-vars.mk
  hack/make-tools.mk
Labels: lgtm, approved, bugzilla/valid-bug

#451 hack: update script to print debug output of csv and pods
  hack/install-odf.sh
Labels: lgtm, approved

#450 controllers: Shut down OCS client CSV pods if not in provider mode
  controllers/storagesystem_controller.go
  controllers/subscriptions.go
Labels: lgtm, approved

#459 Syncing latest changes from main for odf-operator
  controllers/storagesystem_controller.go
  controllers/subscriptions.go
  hack/install-odf.sh
Labels: lgtm, approved

#373 Bug 2263474:[release-4.13] bundle: Modify the name and reference of the sample storagesystem
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/samples/ibm-flashsystemcluster-storagesystem.yaml
  config/samples/ocs-storagecluster-storagesystem.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#372 Bug 2263473:[release-4.14] bundle: Modify the name and reference of the sample storagesystem
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/samples/ibm-flashsystemcluster-storagesystem.yaml
  config/samples/ocs-storagecluster-storagesystem.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
