Repository red-hat-storage/odf-operator, pull requests merged in 2025-07, with the labels that each got.

#640 [release-4.18] godeps: update ibm operator apis hash to fix cachito downstream builds
  go.sum
  hack/make-project-vars.mk
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug

#641 update ibm-storage-odf-operator to 1.8.0
  Makefile
  bundle/odf-dependencies/metadata/dependencies.yaml
  bundle/odf-operator/manifests/odf-operator-pkgs-config-4.19.0_v1_configmap.yaml
  catalog/ibm-csi.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  catalog/odf-dependencies.yaml
  config/manager/configmap.yaml
  hack/install-odf.sh
  hack/make-bundle-vars.mk
  hack/make-files.mk
  pkg/deploymanager/operatorscaler.go
Labels: lgtm, approved

#648 Syncing latest changes from main for odf-operator
  Makefile
  bundle/odf-dependencies/metadata/dependencies.yaml
  bundle/odf-operator/manifests/odf-operator-pkgs-config-4.19.0_v1_configmap.yaml
  catalog/ibm-csi.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  catalog/odf-dependencies.yaml
  config/manager/configmap.yaml
  hack/install-odf.sh
  hack/make-bundle-vars.mk
  hack/make-files.mk
  pkg/deploymanager/operatorscaler.go
Labels: lgtm, approved

#647 generate a cnsa-dependencies bundle
  Makefile
  bundle.cnsa.deps.Dockerfile
  bundle.odf.deps.Dockerfile
  bundle/cnsa-dependencies/manifests/cnsa-dependencies.clusterserviceversion.yaml
  bundle/cnsa-dependencies/metadata/annotations.yaml
  bundle/cnsa-dependencies/metadata/dependencies.yaml
  config/bundles/cnsa-dependencies/csv.yaml
  config/bundles/cnsa-dependencies/kustomization.yaml
  config/bundles/odf-dependencies/csv.yaml
  config/bundles/odf-dependencies/kustomization.yaml
  hack/make-bundle-vars.mk
  hack/make-files.mk
Labels: lgtm, approved

#651 add cnsa-dependencies bundle to the catalog
  .github/workflows/docker-build.yaml
  Makefile
  catalog/cnsa-dependencies.yaml
  catalog/index.yaml
  catalog/snapshotter.yaml
  hack/make-files.mk
Labels: lgtm, approved

#654 update golangci lint version
  .github/workflows/conf/golangci-lint.yaml
  .github/workflows/golangci-lint.yaml
  controllers/subscriptions.go
  e2e/setup_teardown.go
Labels: lgtm, approved

#644 DFBUGS-3582:[release-4.18] update ibm-storage-odf-operator to 1.8.0
  bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  hack/make-bundle-vars.mk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#621 DFBUGS-1369:[release-4.18] bundle: add uninstall warning for console
  bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-low

#634 DFBUGS-2876:[release-4.17] controllers: explicitly set client operator Deployment replicas
  controllers/subscriptions.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#660 DFBUGS-3585: [release-4.15] update ibm-storage-odf-operator to 1.8.0
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  hack/make-bundle-vars.mk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#661 DFBUGS-3694:[release-4.14] bundle: add uninstall warning for console
  bundle/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-low
