Repository red-hat-storage/odf-operator, pull requests merged in 2025-05, with the labels that each got.

#517 DFBUGS-1677:[release-4.18] update ibm odf operator to 1.7.0
  bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  controllers/subscriptions.go
  controllers/subscriptions_test.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#569 DFBUGS-1918:[release-4.17] update ibm odf operator to 1.7.0
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#571 DFBUGS-1920:[release-4.15] update ibm odf operator to 1.7.0
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#570 DFBUGS-1919:[release-4.16] update ibm odf operator to 1.7.0
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#613 DFBUGS-2486:[release-4.18] update ibm odf operator to 1.7.1
  bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/valid-reference

#617 bundle: update ibm bundle to 1.7.1
  bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/configmap.yaml
  hack/make-bundle-vars.mk
Labels: lgtm, approved

#619 add odf-snapshot-controller bundle
  Makefile
  bundle/odf-dependencies/manifests/odf-dependencies.clusterserviceversion.yaml
  bundle/odf-dependencies/metadata/dependencies.yaml
  bundle/odf-operator/manifests/odf-operator-manager-config_v1_configmap.yaml
  bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
  catalog/index.yaml
  catalog/odf-dependencies.yaml
  catalog/odf-snapshot-controller.yaml
  config/manager/configmap.yaml
  hack/install-odf.sh
  hack/make-bundle-vars.mk
  hack/make-files.mk
Labels: lgtm, approved
