Repository red-hat-storage/odf-operator, pull requests merged in 2025-06, with the labels that each got.

#628 bundle: remove the storagesystem crd from the bundle
  bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
  bundle/odf-operator/manifests/odf.openshift.io_storagesystems.yaml
  config/crd/kustomization.yaml
Labels: lgtm, approved

#629 Update CSV to support initialization link feature of OLM
  bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#614 DFBUGS-2557:[release-4.17] update ibm odf operator to 1.7.1
  bundle/manifests/odf-operator-manager-config_v1_configmap.yaml
  catalog/ibm.yaml
  catalog/index.yaml
  config/manager/manager.env
  controllers/defaults.go
  hack/make-bundle-vars.mk
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/valid-reference

#631 DFBUGS-2118:[release-4.19] Update CSV to support initialization link feature of OLM
  bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#632 Syncing latest changes from main for odf-operator
  bundle/odf-operator/manifests/odf-operator.clusterserviceversion.yaml
  bundle/odf-operator/manifests/odf.openshift.io_storagesystems.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/odf-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#636 controllers: Skip cleanup controller on fresh installs
  controllers/cleanup_controller.go
Labels: lgtm, approved

#637 Syncing latest changes from main for odf-operator
  controllers/cleanup_controller.go
Labels: lgtm, approved
